# Generated by Django 4.2.3 on 2024-06-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='emaill',
            new_name='email',
        ),
    ]
